global:
  scrape_interval: 3s

scrape_configs:
  - job_name: 'sync-socket'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '172.17.0.1:8080' ]
        labels:
          application: 'reactiveSockets'


